// src/components/Button.svelte
<script lang="ts">
	import type { Snippet } from "svelte";

	const BASE_CLASSES =
		"p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-zinc-600 transition-colors";

	let {
		class: className = "",
		children,
		...props
	}: { class?: string; children?: Snippet } & any = $props();
</script>

<button {...props} class="{className} {BASE_CLASSES}">
	{#if children}
		{@render children()}
	{/if}
</button>

// src/components/Button.tsx
import type { ButtonHTMLAttributes } from "react";

const BASE_CLASSES = "p-2 rounded-lg bg-white border border-gray-200 hover:bg-gray-100 dark:bg-zinc-700 dark:border-zinc-500 dark:hover:bg-zinc-600 transition-colors";

export function Button({ className, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement>) {
	return (
		<button
			{...props}
			className={`${className} ${BASE_CLASSES}`}
		>
			{children}
		</button>
	)
}

export function LinkButton({ className, children, ...props }: React.AnchorHTMLAttributes<HTMLAnchorElement>) {
	return (
		<a
			{...props}
			className={`${className} ${BASE_CLASSES}`}
		>
			{children}
		</a>
	)
}
